///////////////////////////////////////////////////////////
//  Product.cs
//  Implementation of the Class Product
//  Generated by Enterprise Architect
//  Created on:      05-五月-2013 16:32:54
//  Original author: 吉桂昕
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using MyTools.Framework.Common;
using Top.Api.Request;
using Top.Api.Util;

namespace MyTools.TaoBao.DomainModule
{

    /// <summary>
    /// 类目API taobao.itemprops.get 获取标准商品类目属性（包括：货号、品牌、衣长等）
    /// 注：1，货号，是放在input_str，input_pids
    /// 中，如：【（input_pids：input_str）（1632501：238286）】2，品牌，如果淘宝类目中有该品牌如：那么就加到props中，如果没有，需
    /// 要自定义品牌者加到input_str，input_pids，如：【（input_pids：input_str）（20000：莱克）】3,
    /// SUK（销售）属性，sku_properties中有的属性props也必须存在。sku_properties中以“，”分开。
    /// </summary>
    public class Product : ItemAddRequest
    { 
        /// <summary>
        /// 市场价
        /// </summary>
        public virtual double MarketPrice { get; set; }

        /// <summary>
        /// 总售价
        /// </summary>
        public virtual double SalePrice { get; set; }
         
        /// <summary>
        /// 销量
        /// </summary>
        public virtual int SalesVolume { get; set; }


        public List<ProductColor> ColorList { get; set; }
         
        /// <summary>
        /// 销售属性与淘宝的销售属性对应，如。key: 155/80A(S); 20509:28314
        /// </summary>
        public Dictionary<string, string> BSizeToTSize { get; set; }


        public Product()
        {
            FreightPayer = "buyer";
            Type = "fixed";
            StuffStatus = "new";
            LocationState = SysConst.LocationState;
            LocationCity = SysConst.LocationCity;
        }

        public virtual void Dispose()
        {

        }

    }

//end Product
}
