//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyTools.TaoBao.DomainModule {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyTools.TaoBao.DomainModule.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 没有获取到认证Code 的本地化字符串。
        /// </summary>
        public static string Exception_NotFoundAuthorizedCode {
            get {
                return ResourceManager.GetString("Exception_NotFoundAuthorizedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产入的Url无效 的本地化字符串。
        /// </summary>
        public static string Exception_UrlInvalid {
            get {
                return ResourceManager.GetString("Exception_UrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过该XPATH没有获取到正确的数据,{0} 的本地化字符串。
        /// </summary>
        public static string Exception_XPathGetDataError {
            get {
                return ResourceManager.GetString("Exception_XPathGetDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在 [{0}] 方法中参数不能为空 的本地化字符串。
        /// </summary>
        public static string ExceptionTemplate_MethedParameterIsNullorEmpty {
            get {
                return ResourceManager.GetString("ExceptionTemplate_MethedParameterIsNullorEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 得到产品列表失败 的本地化字符串。
        /// </summary>
        public static string Log_GetGoodsListFailure {
            get {
                return ResourceManager.GetString("Log_GetGoodsListFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 得到卖家仓库中的商品出错 的本地化字符串。
        /// </summary>
        public static string Log_GetInventoryGoodsFailure {
            get {
                return ResourceManager.GetString("Log_GetInventoryGoodsFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 得到在售商品出错 的本地化字符串。
        /// </summary>
        public static string Log_GetOnSaleGoodsFailure {
            get {
                return ResourceManager.GetString("Log_GetOnSaleGoodsFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GoodsSn:{0}-&gt;已经存在不能再上传  的本地化字符串。
        /// </summary>
        public static string Log_GoodsAlreadyExist {
            get {
                return ResourceManager.GetString("Log_GoodsAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NumlId:{0}-&gt;正在下架... 的本地化字符串。
        /// </summary>
        public static string Log_GoodsDelisting {
            get {
                return ResourceManager.GetString("Log_GoodsDelisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NumId:{0} -&gt;产品下架失败 的本地化字符串。
        /// </summary>
        public static string Log_GoodsDelistingFailure {
            get {
                return ResourceManager.GetString("Log_GoodsDelistingFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NumlId:{0}-&gt;下架成功 的本地化字符串。
        /// </summary>
        public static string Log_GoodsDelistingSuccess {
            get {
                return ResourceManager.GetString("Log_GoodsDelistingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布产品：{0} 发布失败 的本地化字符串。
        /// </summary>
        public static string Log_PublishGoodsFailure {
            get {
                return ResourceManager.GetString("Log_PublishGoodsFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-&gt;正在发布... 的本地化字符串。
        /// </summary>
        public static string Log_PublishGoodsing {
            get {
                return ResourceManager.GetString("Log_PublishGoodsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布产品：{0} 已发布成功。numId:{1} 的本地化字符串。
        /// </summary>
        public static string Log_PublishGoodsSuccess {
            get {
                return ResourceManager.GetString("Log_PublishGoodsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传销售图片：失败。 的本地化字符串。
        /// </summary>
        public static string Log_PublishSaleImgFailure {
            get {
                return ResourceManager.GetString("Log_PublishSaleImgFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NumlId:{0}-&gt;正在上传销售图片... 的本地化字符串。
        /// </summary>
        public static string Log_PublishSaleImging {
            get {
                return ResourceManager.GetString("Log_PublishSaleImging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上传销售图片：成功。numId:{0},图片地址:{1} 的本地化字符串。
        /// </summary>
        public static string Log_PublishSaleImgSuccess {
            get {
                return ResourceManager.GetString("Log_PublishSaleImgSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新产品：更新失败。numId:{0} 的本地化字符串。
        /// </summary>
        public static string Log_UpdateGoodsFailure {
            get {
                return ResourceManager.GetString("Log_UpdateGoodsFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NumIid:{0}-&gt;正在更新... 的本地化字符串。
        /// </summary>
        public static string Log_UpdateGoodsing {
            get {
                return ResourceManager.GetString("Log_UpdateGoodsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新产品：{0} 已更新成功。numId:{1} 的本地化字符串。
        /// </summary>
        public static string Log_UpdateGoodsSuccess {
            get {
                return ResourceManager.GetString("Log_UpdateGoodsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /html/body/div[@class=&apos;content&apos;]/div[2]/div[@class=&apos;copy-code&apos;]/input 的本地化字符串。
        /// </summary>
        public static string SysConfig_AuthorizedCodeXPath {
            get {
                return ResourceManager.GetString("SysConfig_AuthorizedCodeXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://open.taobao.com/authorize/?appkey={0} 的本地化字符串。
        /// </summary>
        public static string SysConfig_AuthorizeUrl {
            get {
                return ResourceManager.GetString("SysConfig_AuthorizeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 read_colorlist 的本地化字符串。
        /// </summary>
        public static string SysConfig_ColorListId {
            get {
                return ResourceManager.GetString("SysConfig_ColorListId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2013运费模板 的本地化字符串。
        /// </summary>
        public static string SysConfig_DeliveryTemplateName {
            get {
                return ResourceManager.GetString("SysConfig_DeliveryTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 25 的本地化字符串。
        /// </summary>
        public static string SysConfig_EmsFee {
            get {
                return ResourceManager.GetString("SysConfig_EmsFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12 的本地化字符串。
        /// </summary>
        public static string SysConfig_ExpressFee {
            get {
                return ResourceManager.GetString("SysConfig_ExpressFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /html/body/div/div[@class=&apos;details_dir&apos;]/a[2] 的本地化字符串。
        /// </summary>
        public static string SysConfig_GetBanggoProductBrandCodeXPath {
            get {
                return ResourceManager.GetString("SysConfig_GetBanggoProductBrandCodeXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /html/body/div/div[@class=&apos;details_dir&apos;]/a[5] 的本地化字符串。
        /// </summary>
        public static string SysConfig_GetBanggoProductCatalogXPath {
            get {
                return ResourceManager.GetString("SysConfig_GetBanggoProductCatalogXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /html/body/div/div[@class=&apos;details_dir&apos;]/a[3] 的本地化字符串。
        /// </summary>
        public static string SysConfig_GetBanggoProductCategoryXPath {
            get {
                return ResourceManager.GetString("SysConfig_GetBanggoProductCategoryXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /html/body/div/div[@class=&apos;details_dir&apos;]/a[4] 的本地化字符串。
        /// </summary>
        public static string SysConfig_GetBanggoProductParentCatalogXPath {
            get {
                return ResourceManager.GetString("SysConfig_GetBanggoProductParentCatalogXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Api 的本地化字符串。
        /// </summary>
        public static string SysConfig_GetDataByApi {
            get {
                return ResourceManager.GetString("SysConfig_GetDataByApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Local 的本地化字符串。
        /// </summary>
        public static string SysConfig_GetDataByLocal {
            get {
                return ResourceManager.GetString("SysConfig_GetDataByLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Api 的本地化字符串。
        /// </summary>
        public static string SysConfig_GetDataWay {
            get {
                return ResourceManager.GetString("SysConfig_GetDataWay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //*[@id=&apos;goods_model&apos;]//img[@src=&apos;http://s.mb-go.com/pub7/style/images/grey.gif&apos;] 的本地化字符串。
        /// </summary>
        public static string SysConfig_GetGoodsModeImgGreyXPath {
            get {
                return ResourceManager.GetString("SysConfig_GetGoodsModeImgGreyXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://act.banggo.com/Price/getGoodsPrice?r={0}&amp;callback=&amp;goods_sn={1} 的本地化字符串。
        /// </summary>
        public static string SysConfig_GetGoodsPriceByBanggoUrl {
            get {
                return ResourceManager.GetString("SysConfig_GetGoodsPriceByBanggoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \d{6} 的本地化字符串。
        /// </summary>
        public static string SysConfig_GetGoodsSnByUrlRegex {
            get {
                return ResourceManager.GetString("SysConfig_GetGoodsSnByUrlRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 market_price 的本地化字符串。
        /// </summary>
        public static string SysConfig_GetMarketPriceId {
            get {
                return ResourceManager.GetString("SysConfig_GetMarketPriceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 div[@class=&apos;goods_price&apos;]/del 的本地化字符串。
        /// </summary>
        public static string SysConfig_GetMarketPriceXPath {
            get {
                return ResourceManager.GetString("SysConfig_GetMarketPriceXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://act.banggo.com/Ajax/cartAjax?time={0}&amp;ajaxtype=color_size&amp;type=color&amp;code={1}&amp;r_code=&amp;goods_sn={2} 的本地化字符串。
        /// </summary>
        public static string SysConfig_GetProductByBanggoAvailableColorUrl {
            get {
                return ResourceManager.GetString("SysConfig_GetProductByBanggoAvailableColorUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://act.banggo.com/Ajax/cartAjax?time={0}&amp;ajaxtype=color_size&amp;type=size&amp;code={1}&amp;r_code={2}&amp;goods_sn={3} 的本地化字符串。
        /// </summary>
        public static string SysConfig_GetProductByBanggoAvailableSizeUrl {
            get {
                return ResourceManager.GetString("SysConfig_GetProductByBanggoAvailableSizeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //*[@id=&apos;productinfo_div&apos;]//img[@src=&apos;http://s.mb-go.com/pub7/style/images/grey.gif&apos;] 的本地化字符串。
        /// </summary>
        public static string SysConfig_GetProductInfoImgGreyXPath {
            get {
                return ResourceManager.GetString("SysConfig_GetProductInfoImgGreyXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 sale_price 的本地化字符串。
        /// </summary>
        public static string SysConfig_GetSalePriceId {
            get {
                return ResourceManager.GetString("SysConfig_GetSalePriceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 div[@class=&apos;sales&apos;]/p/strong[@class=&apos;red&apos;]/a 的本地化字符串。
        /// </summary>
        public static string SysConfig_GetSalesVolumeXPath {
            get {
                return ResourceManager.GetString("SysConfig_GetSalesVolumeXPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 svip_price 的本地化字符串。
        /// </summary>
        public static string SysConfig_GetSvipPriceId {
            get {
                return ResourceManager.GetString("SysConfig_GetSvipPriceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 vip_price 的本地化字符串。
        /// </summary>
        public static string SysConfig_GetVipPriceId {
            get {
                return ResourceManager.GetString("SysConfig_GetVipPriceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 goods_model 的本地化字符串。
        /// </summary>
        public static string SysConfig_GoodsDescId {
            get {
                return ResourceManager.GetString("SysConfig_GoodsDescId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0.2 的本地化字符串。
        /// </summary>
        public static string SysConfig_ItemWeight {
            get {
                return ResourceManager.GetString("SysConfig_ItemWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2000:4146697; 的本地化字符串。
        /// </summary>
        public static string SysConfig_ME_CITY_BrandProp {
            get {
                return ResourceManager.GetString("SysConfig_ME-CITY_BrandProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2000:29504; 的本地化字符串。
        /// </summary>
        public static string SysConfig_METERSBONWE_BrandProp {
            get {
                return ResourceManager.GetString("SysConfig_METERSBONWE_BrandProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 12 的本地化字符串。
        /// </summary>
        public static string SysConfig_PostFee {
            get {
                return ResourceManager.GetString("SysConfig_PostFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1632501 的本地化字符串。
        /// </summary>
        public static string SysConfig_ProductCodeProp {
            get {
                return ResourceManager.GetString("SysConfig_ProductCodeProp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 productinfo_div 的本地化字符串。
        /// </summary>
        public static string SysConfig_ProductInfoId {
            get {
                return ResourceManager.GetString("SysConfig_ProductInfoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 http://gw.api.taobao.com/router/rest 的本地化字符串。
        /// </summary>
        public static string SysConfig_RealTaobaoServerUrl {
            get {
                return ResourceManager.GetString("SysConfig_RealTaobaoServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 read_sizelist 的本地化字符串。
        /// </summary>
        public static string SysConfig_SizeListId {
            get {
                return ResourceManager.GetString("SysConfig_SizeListId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sku 的本地化字符串。
        /// </summary>
        public static string SysConfig_Sku {
            get {
                return ResourceManager.GetString("SysConfig_Sku", resourceCulture);
            }
        }
    }
}
