///////////////////////////////////////////////////////////
//  IItemCats.cs
//  Implementation of the Interface IItemCats
//  Generated by Enterprise Architect
//  Created on:      08-五月-2013 0:20:04
//  Original author: 吉桂昕
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using Top.Api.Domain;

namespace MyTools.TaoBao.Interface
{
    /// <summary>
    /// 根据该商品所属的父类目和子类目来得到，cid和props
    /// </summary>
    public interface IItemCats  {

        /// <summary>
        /// 根据淘宝的父类目和子类目->获取后台供卖家发布商品的标准商品类目id
        /// </summary>
        /// <param name="parentCatalog">父类目</param>
        /// <param name="childCatalog">子类目</param>        
        string GetCid(string parentCatalog,string childCatalog);

        /// <summary>
        /// 得到淘宝的所有商品类目
        /// </summary>
        /// <returns></returns>
        List<ItemCat> GetAllItemCatByApi(long parentCid);

        //类目API taobao.itemprops.get 获取标准商品类目属性（包括：货号、品牌、衣长等）
        /// <summary>
        /// 类目API taobao.itemprops.get 获取标准商品类目属性（包括：货号、品牌、衣长等）
        /// 注：1，货号，是放在input_str，input_pids 中，如：【（input_pids：input_str）
        /// （1632501：238286）】
        /// 2，品牌，如果淘宝类目中有该品牌如：那么就加到props中，如果没有，需要自定义品牌者加到
        /// input_str，input_pids，如：【（input_pids：input_str）（20000：莱克）】
        /// 3,SUK（销售）属性，sku_properties中有的属性props也必须存在。
        /// sku_properties中以，分开。
        /// </summary>
        /// <param name="cid">淘宝所属类目ID</param>
        List<ItemProp> GetPropsByCid(long cid);


    }
}//end IItemCats